baseurl = "localhost"
title = "Abhinav Borah"
languageCode = "en-us"
paginate = 10

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
EnableThemeToggle = true

# Subtitle for home
homeSubtitle = " "

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = true

# Show a global language switcher in the navigation bar
enableGlobalLanguageMenu = false

enableInlineShortcodes = true

# Metadata mostly used in document's head
description = "My portfolio"
keywords = "homepage, blog, portfolio"
images = [""]

[taxonomies]
category = "blog"
tag = "tags"
series = "series"

[languages]
[languages.en]
title = "Abhinav Borah"
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[languages.en.params]
keywords = ""
readOtherPosts = "Read other posts"
subtitle = ""

[languages.en.params.logo]
logoText = "whoami"
logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

# And you can even create generic menu
[[menu.main]]
identifier = "about"
name = "About"
url = "/about"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"

[[menu.main]]
identifier = "tags"
name = "Topics"
url = "/tags"

[module]
[[module.imports]]
path = "github.com/rhazdon/hugo-theme-hello-friend-ng"
disable = false
